### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by marcmanusch** [FriendsOfShopware/FroshPlatformThumbnailProcessor#104]
### PHP Version

8.2

### Shopware Version

6.5.3.3

### Actual behaviour

![IMG_1925](https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/assets/31078285/f1da592e-40c0-4e4f-a683-929346802480)

### Expected behaviour

Installation is successful 

### Steps to Reproduce?

Install

**Comment by tinect** [comment]
Hi,

I tried installing version 4.0.0 at shopware 6.5.3.3 without problem.

Could you please verify the following things:
- you don't have the plugin on multiple locations (custom/plugins, custom/static-plugins, vendor without link)
- you don't have a manipulated \Shopware\Core\Content\Media\Thumbnail\ThumbnailService

**Comment by marcmanusch** [comment]
Hi, yes I am sure, that I only have the directory custom/plugins and have no manipulation on this service. I tried to install from store and zip file.

how can I get more information?

**Comment by tinect** [comment]
I see you might have FroshTools installed?

please check the tab "Shopware files" for possible manipulated files.

**Comment by marcmanusch** [comment]
Sure...
<img width="1315" alt="Bildschirmfoto 2023-08-14 um 08 13 23" src="https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/assets/31078285/10ae4f9d-3084-45f5-b18b-6a6b568875f1">

**Comment by tinect** [comment]
Is there any way you can give me SSH access to the server?
You are welcome to contact me at http://slack.shopware.com/

**Comment by marcmanusch** [comment]
Sorry thats not possible. I noticed a strange thing. When I try to install it over SSH, it tells me its already installed, but its not.
<img width="704" alt="Bildschirmfoto 2023-08-14 um 10 51 09" src="https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/assets/31078285/2ed123ba-741c-43da-8cc6-b96a0e429c6f">

Let me check the Database...

**Comment by marcmanusch** [comment]
Hmmm...
<img width="1458" alt="Bildschirmfoto 2023-08-14 um 10 57 44" src="https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/assets/31078285/e8b32103-bf9f-4b2b-a049-52fefd665dc5">

**Comment by marcmanusch** [comment]
There is a similar issue for an other project, in this case the composer.json makes the problem.
https://github.com/phpstan/phpstan/issues/5263

https://github.com/phpstan/phpstan-src/commit/0f8ead706ba4b514e4a511c743645c065f52f195

FROM: "nikic/php-parser": "4.11.0",
TO:	"nikic/php-parser": "dev-master#c758510a37218d631fd10f67bca5bccbfef864fa as 4.11.0",

**Comment by marcmanusch** [comment]
**Solved.**
<img width="1111" alt="Bildschirmfoto 2023-08-14 um 12 13 24" src="https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/assets/31078285/19c4ac07-c811-4220-af54-8e5811376377">
