### ISSUE TITLE
The used service does not resize the image. sample

### ISSUE THREAD

**Issue by bjbommer** [FriendsOfShopware/FroshPlatformThumbnailProcessor#106]
### Question

Hi,
we installed the Plugin in out Testsystem. A plain Shopware 6.5.4.0 installation and your Plugin, with the newest Version 4.0.0. 

On the configuration page, i activeted the Plug and clicked "save and test". The page reload and i get the Message: "The used service does not resize the image. sample URL: ...." If i open the Demo-Image-Link (...froshthumbnailprocessortestimage.jpg?width=200) in my Browser,  i get the image with the dimension 1024x1024.
Not with 200x200. 

I also tried to regenerate the media files with media:generate-thumbnail and i cleared the cache, but this have no effect. 

Do i need a server module or something else?

**Comment by tinect** [comment]
You need to set up an external service. Here are a few examples: https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/discussions/categories/patterns

The plugin does not create thumbnails, it manipulates the urls for the shop and api to have on-the-fly thumbnails.

**Comment by tinect** [comment]
if you need further help, contact us in friendsofshopware channel in slack.shopware.com
