### ISSUE TITLE
Problems installing/updating it through the store on 6.5.6.0

### ISSUE THREAD

**Issue by qx54** [FriendsOfShopware/FroshPlatformThumbnailProcessor#114]
### Question

I just updated Shopware from 6.4 to 6.5 (it automatically updated to 6.5.6.0) and get the following error when I try to install this extension through the Shopware store:

> Die Erweiterung steht in der aktuellen Version noch nicht zur Verfügung. Versuche es später noch einmal.

It was previously already installed but for some reason it was not possible to update it after the Shopware update to 6.5. Therefore I totally uninstalled and removed it in order to re-install it, with above result.

Installing manually worked, but I'd prefer to have it installed through the store.

**Comment by tinect** [comment]
Hey,

what olugin version did you download and install?
