### ISSUE TITLE
6.5.7.3 Compatibility / Exception on Activation

### ISSUE THREAD

**Issue by tanmarradtke** [FriendsOfShopware/FroshPlatformThumbnailProcessor#121]
### Please describe the feature you would like to see implemented.

The plugin is currently not marked as compatible with 6.5.7.3
https://store.shopware.com/frosh69611263569f/thumbnailprocessor-mit-webp-unterstuetzung.html

We tried it anyway because we thought the definition simply wasn't updated yet but on activation we get the following error

Method createThumbnailsForSizes in class Shopware\Core\Content\Media\Thumbnail\ThumbnailService is missing

**Comment by tinect** [comment]
I did not check it with 6.5.7.3, yet.

Did you try it by clearing the cache before?

**Comment by tanmarradtke** [comment]
Clearing cache didn't solve the problem. Might also be a PHP 8.2 issue. We also switched to to 8.2 with the update.

**Comment by tinect** [comment]
You might have noticed, I'm a little slowed down due to illness.

Do you have the most recent version of the plugin installed? Please try to uninstall and remove the plugin and install it again. 
I'll try the recent version with 6.5.7.3 again in the next days.

**Comment by tinect** [comment]
@tanmarradtke No problem, you're welcome :-)
