### ISSUE TITLE
Dependency Injection of the ThumbnailService fails

### ISSUE THREAD

**Issue by M-arcus** [FriendsOfShopware/FroshPlatformThumbnailProcessor#123]
### PHP Version

8.2.14

### Shopware Version

5.7.3

### Plugin Version

4.0.1

### Actual behaviour

```
$ bin/console plugin:install -ac FroshPlatformThumbnailProcessor

Shopware Plugin Lifecycle Service
=================================

 Install 1 plugin(s):
 * ThumbnailProcessor mit Webp-Unterstützung (v4.0.1)

17:16:28 CRITICAL  [console] Error thrown while running command "plugin:install -ac FroshPlatformThumbnailProcessor". Message: "Class "Frosh\ThumbnailProcessor\DependencyInjection\ThumbnailService" not found" ["exception" => Error { …},"command" => "plugin:install -ac FroshPlatformThumbnailProcessor","message" => "Class "Frosh\ThumbnailProcessor\DependencyInjection\ThumbnailService" not found"]

In Shopware_Core_KernelProdContainer.php line 54057:
                                                                                                                                                                          
  Attempted to load class "ThumbnailService" from namespace "Frosh\ThumbnailProcessor\DependencyInjection".                                                               
  Did you forget a "use" statement for e.g. "Shopware\Core\Content\Media\Thumbnail\ThumbnailService" or "Frosh\ThumbnailProcessor\DependencyInjection\ThumbnailService"?  
                                                                                                                                                                          

plugin:install [-r|--refresh] [-c|--clearCache] [--skip-asset-build] [-a|--activate] [--reinstall] [--] <plugins>...

```

### Expected behaviour

Plugin gets installed, Class gets injected

### Steps to Reproduce?

Simple Composer require and following Installation in a Flex Setup

**Comment by tinect** [comment]
could you please run a simple „bin/console“ before? there are files auto generated. I assume they are not booted at the moment.

**Comment by M-arcus** [comment]
The error still occurs. Even after deleting the 2 files, clearing opcache and reinstalling the plugin

**Comment by tinect** [comment]
did you remove the cache-folders for safety, too? tell me something about your environment.

**Comment by M-arcus** [comment]
Yes, I deleted those with `rm -rf var/cache` and the `bin/console cache:clear` command after removing the 2 generated files from the directory.

The local environment is a devenv setup based on the kellerkinder devenv repo. The error does not occur there.

The server environment is a normal LAMP stack with a strict opcache. The deployment is based on the shopware recipe from deployer. The composer install happens in the github action, not on the server. Is this an issue?

Can I add the 2 files manually via patch? Or is the dynamic generation absolutely necessary?

The

**Comment by tinect** [comment]
it is really neccessary. otherwise you have to create files per shopware version.

in CI: after composer:install, you tried adding a simple bin/console or bin/ci ?

**Comment by M-arcus** [comment]
> it is really neccessary. otherwise you have to create files per shopware version.

I have added the local version of the 2 files as a composer patch for now. Now it is working on both systems. Which is weird, since they were identical with the server version. So the error is definitely not with the plugin. I will close this issue.

> in CI: after composer:install, you tried adding a simple bin/console or bin/ci ?

Yes, sadly, this did not fix the issue.

> on the other side: I assume problems with strict opcache. does your setup habe fpm? are you using cachetool?

Yes, cachetool is installed and resets the cache. The fpm reload also does not fail
