### ISSUE TITLE
Wrong Path after switching active on

### ISSUE THREAD

**Issue by ldehne-comcreate** [FriendsOfShopware/FroshPlatformThumbnailProcessor#125]
### Question

After turning on the active switch on the Plugin Configuration the plugin change the hole Path to a full wrong path and placing an dubble // infront of media. 
Did i doing something wrong? 
Using BunnyCDN
Used Pattern: {mediaUrl}/{mediaPath}?width={width}
Just with the Plugin Active
https://cdn.gruenwaren.de/media/6d/fa/67/1707983229/38cd72d75a5e15d8e4c2c408bc59691a.JPG
After turning the Active Switch in the Plugin Configuration
https://cdn.gruenwaren.de//media/86/86/45/1707986829/38cd72d75a5e15d8e4c2c408bc59691a.JPG?width=3000

**Comment by ldehne-comcreate** [comment]
This is the link after deleting the / from the Pattern and deleting SW Cache Redis Cache and restartet php and apache:
https://cdn.gruenwaren.de/media/86/86/45/1707986829/38cd72d75a5e15d8e4c2c408bc59691a.JPG?width=400
still wrong path but the dubble slash is gone

**Comment by tinect** [comment]
I mean:

you are sure, the "new" url came from activating the plugin? did you clear the cache before?
Wrong paths come wrong miss-configurated `default_cdn_strategy` or env `SHOPWARE_CDN_STRATEGY_DEFAULT` which does not fit the installation where the database is from. Which was `id` for some time.

**Comment by tinect** [comment]
@ldehne-comcreate were you able to evaluate the setting?

**Comment by tinect** [comment]
We'll close here due to inactivity.

**Comment by ldehne-comcreate** [comment]
Hey @tinect ,

Apologies for the delayed response. I was ill and unable to reply earlier. 
We don't have any SHOPWARE_CDN_STRATEGY_DEFAULT in our .env file, but we do have the following in our services.yaml:
```
default_cdn_strategy: 'physical_filename'
shopware.cdn.strategy: '%env(default:default_cdn_strategy:SHOPWARE_CDN_STRATEGY_DEFAULT)%'
```
Also, I can confirm that the "new" URL originated from activating the plugin. 
I cleared the cache both before and after activating the plugin.

**Comment by tinect** [comment]
Could you please

**Comment by ldehne-comcreate** [comment]
Same Issuse:
Without activated Plugin: https://cdn.gruenwaren.de/media/45/63/c3/1707917441/f6c3cf66a2be30cf9a1106b8239bcc79.JPG
With activated Plugin: https://cdn.gruenwaren.de/media/7a/b3/18/1707921041/f6c3cf66a2be30cf9a1106b8239bcc79.JPG?width=400
did i need to process the thumbnails again after changing SHOPWARE_CDN_STRATEGY_DEFAULT to id?

**Comment by ldehne-comcreate** [comment]
I cleared the thumbnail db and done media:generate-thumbnails again same problem.

**Comment by ldehne-comcreate** [comment]
i just searched in our db but found nothing
7a/b3/18/1707921041

**Comment by tinect** [comment]
What Shopware- and Plugin-Version are you running?

**Comment by ldehne-comcreate** [comment]
SW: 6.5.8.6
Plugin: 4.0.2

**Comment by tinect** [comment]
Hey @ldehne-comcreate,

I did my best to try reproducing your issue. Sadly, I was unable to reproduce it in any way.

Your sample urls show different timestamps where the urls came from:
1707921041 vs 1707917441

This is exactly one hour, which might be a problem coming from plugins manipulating the timezone.
I don't see any modification by this plugin.

Can you reproduce it in any default installation with just this plugin? Please send me credentials to check it in such a test shop.
Otherwise, please check the environment.

**Comment by ldehne-comcreate** [comment]
Hey @tinect,

You've been a great help! We have a connector for PlentyMarkets that uploads all images. However, we've encountered an issue: the timestamp is saved an hour earlier. We need to address this discrepancy. Thank you so much.
