### ISSUE TITLE
Problems with 6.5.8.7?

### ISSUE THREAD

**Issue by michaadm** [FriendsOfShopware/FroshPlatformThumbnailProcessor#127]
### Question

Hi, are there anny knowen problems with 6.5.8.7? Its not marked ready for 6.5.8.7... we testeted it in our stage and didn't saw any problems - but we didn't connect our stage to cloudflare, to avoid the extra traffic, so we could not see fully if it works and and are waiting for update our live enviroment.

**Comment by tinect** [comment]
Hey, plugin is now marked as compatible in store.

You might want to use the public packagist, while it is more recent without any delay and more stable. https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor?tab=readme-ov-file#by-composer
