### ISSUE TITLE
Bad Request Frosh\ThumbnailProcessor\FroshPlatformThumbnailProcessor

### ISSUE THREAD

**Issue by srygt** [FriendsOfShopware/FroshPlatformThumbnailProcessor#129]
### Question

Wenn wir das Plugin „ThumbnailProcessor mit Webp-Unterstützung“ auf unserer Shopware-Version 6.5.8.5-Website installieren, erhalten wir die folgende Fehlermeldung. Wie können wir es lösen?

Bad Request
The class "Frosh\ThumbnailProcessor\FroshPlatformThumbnailProcessor" is not found. Probably an class loader error. Check your plugin composer.json

![Screenshot from 2024-04-09 11-33-11](https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/assets/53877866/684d4666-6e8b-431a-8454-3612c960c778)

**Comment by tinect** [comment]
Hi @srygt,

what plugin version have you intalled and what is the source of the plugin (store, zip, ...)?

**Comment by srygt** [comment]
Hi @tinect 
ThumbnailProcessor mit Webp-Unterstützung
Version: 4.0.2

We use it on the tabak-xxl.de website.
Shopware Version: 6.5.8.5

**Comment by tinect** [comment]
Sadly, this sounds like a problem with your opcache-settings. Could you please check it?

**Comment by tinect** [comment]
Due to inactivity, we will close here.
