### ISSUE TITLE
Shopware 6.6 Cache Busting

### ISSUE THREAD

**Issue by xyng** [FriendsOfShopware/FroshPlatformThumbnailProcessor#131]
### Please describe the feature you would like to see implemented.

From Shopware 6.6 onwards, the path of the file is not necessarily unique. This may lead to caching problems in the used image-service (in our case imgproxy with a simple nginx cache, where we cache based on request uri and headers - other services may work similarly).
The Shopware ADR says a timestamp is added as a query string to allow cache busting.
However, this timestamp seems to not be available in the Pattern Variables of this Plugin.
(If it is available and I'm just too blind to see, a heads up is very much appreciated!)

If I'm not mistaken that information is available in `UrlParams` used in `Frosh\ThumbnailProcessor\Core\Media\MediaUrlGenerator`.
So theoretically the timestamp could be passed to the Template by adding `$value->updatedAt` in this call here.
https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/blob/9ce705d45d0ca17fab62db847ea18f269180c12c/src/Core/Media/MediaUrlGenerator.php#L51

The updatedAt-Value could then be provided as another placeholder here. A suitable name could be `mediaUpdatedAt`.
https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/blob/9ce705d45d0ca17fab62db847ea18f269180c12c/src/Service/ThumbnailUrlTemplate.php#L17

This would probably cause a breaking change in `Frosh\ThumbnailProcessor\Service\ThumbnailUrlTemplateInterface`, since added parameters will make existing implementations of that interface be invalid.

The challenging part would probably be to handle an empty `updatedAt`-Value.
Naïve solutions may be omitting the value or using timestamp `0`.

I think having the possibility of aiding the used service with cache invalidation might be a good thing.
I would be willing to provide a PR adding this feature if you are interested.

**Comment by tinect** [comment]
Hey @xyng,

Thank you for mentioning this again. I forgot it because I never took care of it, while replacing is automatically invalidating the caches on my CDNs side.

I truly appreciate a PR for this. 👍 

One question because you mentioned it:
you have a cache layer in front of imgproxy, don't you? Otherwise, any request for the same image will result in any new processing of imgproxy.

Best Regards,
Sebastian

**Comment by xyng** [comment]
Hi @tinect,

thanks - I'll start preparing one then.

In regards to the cache layer:
Yes, we do. I edited the post around a bit before posting and that part got lost.

**Comment by tinect** [comment]
5.1.0 is released
