### ISSUE TITLE
Shop speed optimisation 

### ISSUE THREAD

**Issue by paraskumar12011996** [FriendsOfShopware/FroshPlatformThumbnailProcessor#138]
### Question

Hello Friends,
I have observed the Shopware Extension “ThumbnailProcessor mit Webp-Unterstützung” as root cause for page speed reduction.
If this plugin is active light house performance for mobile is 29 and desktop is 58
If I deactivate this plugin and verify the light house performance for mobile is 41 and desktop is 73

So can you please suggest me some ways and ideas to improve the speed with this plugin.

Thank you.

**Comment by tinect** [comment]
I will close this issue, while you opened a discussion: https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/discussions/139
