### ISSUE TITLE
https://cxyz.cloudimg.io/www.example.com/media/76/7b/20/1720540348/froshthumbnailprocessortestimage.jpg/200

### ISSUE THREAD

**Issue by paraskumar12011996** [FriendsOfShopware/FroshPlatformThumbnailProcessor#141]
### Question

Hello @tinect ,
The used service does not resize the image. sample url: https://cyagvxzhsa.cloudimg.io/www.example.com/media/76/7b/20/1720540348/froshthumbnailprocessortestimage.jpg/200

I am getting above error when execute save and test.

When I am checking the log of cloud image it is shown /v7/www.example.com/media/76/7b/20/1720540348/froshthumbnailprocessortestimage.jpg/200

Is v7 causing any issue?
Please guide here

**Comment by tinect** [comment]
I assume you do not have set the correct pattern. Please check it.

**Comment by paraskumar12011996** [comment]
![image](https://github.com/user-attachments/assets/de7cb59f-efaa-4139-93b8-675932282d95)

I am already using the pattern as suggested in this above image.
https://TOKEN.cloudimg.io/www.myshop.com/{mediaPath}?w={width}&func=bound&org_if_sml=1

Please let me correct.

**Comment by tinect** [comment]
I'm not sure if I get you right.

Was it correct, or not?
I mean, the link shown in your initial message looks different.

**Comment by tinect** [comment]
Hey @paraskumar12011996 

I'm currently waiting for feedback. Did you check the pattern?

**Comment by tinect** [comment]
I'll close here due to inactivity.
