### ISSUE TITLE
don´t know, why not getting webp 

### ISSUE THREAD

**Issue by PV4Tom** [FriendsOfShopware/FroshPlatformThumbnailProcessor#144]
### Question

Hello Sebastian,
I have installed this plugin without any error and have activated it.
I don´t know, why I do not get pictures with webp.
I checked with chrome "open picturen in new tab".  still it shows png or jpg.

any idea, what to do?

I fully appreciate your time and support.
best regards,
Tom

**Comment by tinect** [comment]
how did you verify it? In DevTools by header content-type?

which service do you use?
