### ISSUE TITLE
Version 6.4.0.0 compatibility

### ISSUE THREAD

**Issue by yunits** [FriendsOfShopware/FroshPlatformThumbnailProcessor#17]
Hi, has anyone tested this with Shopware CE 6.4?
I didn't get it to work..

**Comment by tinect** [comment]
Could you please test the update of thumbnailProcessor? :-)

**Comment by yunits** [comment]
Ok. I will report if it works now :-) thx for your fast response

**Comment by yunits** [comment]
Hi, seems like to work now. Thanks :-)
