### ISSUE TITLE
Weird resizing behavior on listing page when using Bunny CDN

### ISSUE THREAD

**Issue by Proxation-mh** [FriendsOfShopware/FroshPlatformThumbnailProcessor#18]
The integration causes that images resize when scrolling. 

Video URL: https://px.d.pr/MrzpkX

According to bunny CDN Support:
Thank you for that, can you please let me know how you had the CDN configured on the site? There is nothing on our side that should be causing this. 

The issue is also not within the additional "Optimizer" service. That was deactivated and the issue was still there. Just after completely deactivating the CDN, this issue was gone. So therefore we concluded, that the connection must be with the CDN Plugin or BunnyCDN.

**Comment by tinect** [comment]
Closed due to inactivity.
