### ISSUE TITLE
Renaming images fails when using ThumbnailProcessor + Imgproxy

### ISSUE THREAD

**Issue by theuers** [FriendsOfShopware/FroshPlatformThumbnailProcessor#20]
I would like to thank the maintainers for creating/maintaining this awesome plugin.
Thank you!

This issue might be related to https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/issues/19.

## Actual behaviour

Renaming an image in the Shopware Administration fails because the shop tries to rename the image as well as its assigned Thumbails. Thumbnails do not exist physically, causing the operation to fail.

## Expected behaviour

Renaming an image in the Shopware Administration causes the image to be renamed.
The shop does not attempt to rename the assigned thumbails as they are not physically present.

## Environment
PHP 7.4, Shopware v6.3.5.1 Stable Version, ThumbnailProcessor 1.0.15, media-folder connected via FlySystem SFTP-Adapter (different host)
PHP 7.4, Shopware v6.4.1.0 Stable Version, ThumbnailProcessor 1.0.17, standard-location of media-folder (same host)

    
    
## Debugging info 
The ImageProcessor plugin seems to assign thumbnail entities to images, the path/url of these does not exist in the filesystem.
(All good so far)

// Call to thumbnail rename function
https://github.com/shopware/platform/blob/1481b146a3a41b4a9e70524ac2fdf64971e45c31/src/Core/Content/Media/File/FileSaver.php#L220

// Line at which there is a problem because the file was not found
https://github.com/shopware/platform/blob/1481b146a3a41b4a9e70524ac2fdf64971e45c31/src/Core/Content/Media/File/FileSaver.php#L252

The file **media/72/5c/7b/1623333455/Test.png** (image itself) is found in the filesystem and renamed correctly, but  **https:/imgproxy-test-media.test.com/800x/https:/test-media.test.com/media/76/c2/66/1623327029/Test.png** (thumbnail url of imageproxy) cannot be found in the filesytem which causes an error.

For debugging purposes, I patched **FileSaver.php** as follows (just temporary, I am not really happy with this)
```
216         foreach ($currentMedia->getThumbnails() as $thumbnail) {
217             // patch start
218             if(strpos($thumbnail->getUrl(),"http") == 0){continue;}
219             // patch end
220             try {
221                 $renamedFiles = array_merge(
222                     $renamedFiles,
223                     $this->renameThumbnail($thumbnail, $currentMedia, $updatedMedia)
224                 );
225             } catch (\Exception $e) {
226                 $this->rollbackRenameAction($currentMedia, $renamedFiles);
227             }
228         }
```
With this patch present, renaming images worked for me.

Alternatively, there is the possibility to forbid any thumbnail-generation in the media folder settings. Renaming of newly uploaded images worked, but that kinda defeats the purpose and is no viable solution for me.

    
    

## Steps to reproduce

1. Install ThumbnailProcessor-Plugin (if not already present)
2. Configure plugin to use an imageproxy (thumbnail pattern does not need to be valid, "http://localhost:8080/insecure/fit/{width}/{height}/sm/0/plain/{mediaUrl}/{mediaPath}" works as well for error-reproduction)
3. Configure media folder to create at least one type of thumbnail for included images
4. Upload new image to previously configured media folder
5. Try to rename previously added image

**Comment by tinect** [comment]
Dupöicates #19
