### ISSUE TITLE
Warrning: Division by zero error as a result of calculation

### ISSUE THREAD

**Issue by wexollm** [FriendsOfShopware/FroshPlatformThumbnailProcessor#22]
### Question

If it happens that an image is not loaded for some reason or broken you will get the following error: 

 Warning: Division by zero, pointing  to -> src/Resources/views/storefront/utilities/thumbnail.html.twig line 22.

You can avoid that by checking if metaProportion is higher than 0

    {% if metaProportion > 0 %}
        {% set ratio = (metaProportion.width / metaProportion.height)|round(2, 'floor') %}
    {% endif %}

**Comment by tinect** [comment]
Hey @wexollm 
Damn, thank you. Will release a fix tomorrow, latest.
