### ISSUE TITLE
Lazysizes NPM package

### ISSUE THREAD

**Issue by Isengo1989** [FriendsOfShopware/FroshPlatformThumbnailProcessor#26]
### Question

Stupid question - how can I roll out / deploy without having to call bin/build-storefront.sh every time? Wihtout the all.js file is not containing the lazysizes lib and images are not loaded 

We are using a cluster of 3 nodes.

**Comment by tinect** [comment]
Hi, is there any reason you don't use https://packages.friendsofshopware.com/ ?

**Comment by Isengo1989** [comment]
@tinect yes, sometimes we need a quick solution, therefor in the first few testing weeks we version it on our private gitlab server.

I guess it is then bc of the missing dist/storefront/js folder - weird that it was not created.

**Comment by tinect** [comment]
You could use the release-zip 🤔
