### ISSUE TITLE
bin/build-storefront.sh error

### ISSUE THREAD

**Issue by treffner** [FriendsOfShopware/FroshPlatformThumbnailProcessor#27]
### PHP Version

7.4

### Shopware Version

6.4.3

### Actual behaviour

Error when using bin/build-storefront.sh.

`# Webpack Plugin Injector: Plugin "FroshPlatformThumbnailProcessor" injected with custom config

✖ Shopware 6 Storefront
  Compiled with some errors in 16.14s

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
   353 modules

ERROR in /custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src/main.js
Module not found: Error: Can't resolve 'lazysizes' in '/custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src'

ERROR in /custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src/main.js
Module not found: Error: Can't resolve 'lazysizes/plugins/attrchange/ls.attrchange' in '/custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src'

ERROR in /custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src/main.js
Module not found: Error: Can't resolve 'lazysizes/plugins/native-loading/ls.native-loading' in '/custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src'

ERROR in /custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src/main.js
Module not found: Error: Can't resolve 'lazysizes/plugins/object-fit/ls.object-fit' in '/custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src'

ERROR in /custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src/main.js
Module not found: Error: Can't resolve 'lazysizes/plugins/parent-fit/ls.parent-fit' in '/custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront/src'
npm ERR! code 2
npm ERR! path /vendor/shopware/storefront/Resources/app/storefront
npm ERR! command failed
npm ERR! command sh -c NODE_ENV=production webpack --config webpack.config.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/acf/.npm/_logs/2021-08-17T14_40_50_440Z-debug.log
`

### Expected behaviour

No error.

### Steps to Reproduce?

bin/build-storefront.sh

I know that in an ideal world bin/build-storefront.sh should not be required on a production server.
But in this case the saferpay payment plugin requires it for shopware 6.4+.

My current workaround is to deactivate this plugin when I have to to run bin/build-storefront.sh and reactivate afterwards.

**Comment by tinect** [comment]
There won't be node_moduled shipped . Therefore please check:  https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor#from-source

**Comment by treffner** [comment]
I can confirm that running 
```bash
cd custom/plugins/FroshPlatformThumbnailProcessor/src/Resources/app/storefront
npm install
`
fixes bin/build-storefront.sh for me.
