### ISSUE TITLE
imgProxy Patter Version 3.0.0 Issue

### ISSUE THREAD

**Issue by vekkon** [FriendsOfShopware/FroshPlatformThumbnailProcessor#44]
### PHP Version

8

### Shopware Version

6.4.8.1

### Actual behaviour

Currently ":" from "rt:fit" and other parts from the pattern are URL encoded to "rt%3Afit".
Due to this encoding, the image URL is not correct anymore and no images are shown.

### Expected behaviour

: should not be encoded or decoded once the site is parsed

### Steps to Reproduce?

1. Install the plugin
2. Configure it to use with imgProxy
3. Go to the frontend > no images will appear
4. Inspect the browser and look into the src tag of the images > you will find url encoded URLs which cause the issues

**Comment by tinect** [comment]
Thabk you for creating this issue.

There is a dreaft forcing this issue: #41 
But I will have a look next days to find a better way.

**Comment by vekkon** [comment]
Hi @tinect 
Thanks for answering and working on this project. 
I saw the draft #41 but this only fixes product images, not logos or slider images.

**Comment by tinect** [comment]
Hi @vekkon 

Could you please give more information regarding the behavior to `logos` and `slider images`?
This sounds really unsuitable to the issue or fix, when others work.
