### ISSUE TITLE
Does not seem to work with images from shopping experiences

### ISSUE THREAD

**Issue by haarhoff-frs** [FriendsOfShopware/FroshPlatformThumbnailProcessor#46]
### Question

After some experimentation with imgproxy and one little change to the plugins source code (found one more rouge sw_encode_media, will try to create a PR later), I got the plug in working okay.
Just one thing, is it correct that it does not work for background images set in shopping experiences, as these are not using thumbnails? If not, is there any way to work around this? These are the pictures that I want to deliver as WEBP the most ;)

**Comment by tinect** [comment]
Thank you for the PR.

can you please tell me the element name you mean?

But generally: if the image output is not using the thumbnail-system of shopware, this will not have been touched.

**Comment by haarhoff-frs** [comment]
We are using the "text-on-image" element. And yes, it does not seem to use the thumbnail system. I'll have a more detailed look next week, if I can change that by overriding the element via the template system, I haven't looked that thoroughly at shopping experiences yet, and I'm quite new to Shopware in general.

**Comment by tinect** [comment]
Just checked this, text-on-image works great on my side. And there are thumbnails loaded.
![image](https://user-images.githubusercontent.com/135993/161337075-3ad9662b-56a8-4ec2-a531-876b43921a50.png)

Keep me posted :-)
