### ISSUE TITLE
Height parameter in template ignored

### ISSUE THREAD

**Issue by ollihfaa** [FriendsOfShopware/FroshPlatformThumbnailProcessor#49]
### PHP Version

7.4

### Shopware Version

6.4.10.0

### Actual behaviour

height parameter is ignored for custom templates

### Expected behaviour

height parameter is also recognized.

### Solution

Frosh\ThumbnailProcessor\Service\ThumbnailUrlTemplate.php

on Line 22 ff code should look like this...

`    public function getUrl(string $mediaUrl, string $mediaPath, string $width, string $height = ''): string
    {
        return str_replace(
            ['{mediaUrl}', '{mediaPath}', '{width}', '{height}'],
            [$mediaUrl, $mediaPath, $width, $height],
            $this->getPattern()
        );
    }`

### Steps to Reproduce?

Configure plugin with any custom template, having "{width}x{height}" parameters.
Upload a rectangular picture.
See the error message produced.

**Comment by tinect** [comment]
This repository you posted the issue belongs to the plugin for shopware 5. Therefore, I've transferred the issue.

Regarding the issue:
This is intended. Lazysizes calculates the width regarding the calculated aspectratio.
https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/commit/7f7973b88463b6251e3cae5a63b4bb581c7c4a4e#diff-e34d65258c5eb2cf1dee05e64355e4cc520dd816c4986e2b3c41b639e8b7c8abR8

**Comment by ollihfaa** [comment]
Hello Sebastian,

 

thank you for transfering my issue to the correct channel.
Actually we don't need my code snippet anymore then, I thought the problem was that the height parameter is always ignored and in the plugin description you also talk about 4 parameters, but only mention 3.

As it turns out things are working without the correct width/height parameters, watch this thumbnail from my product detail page...

https://d2welcj32ydj49.cloudfront.net/fit-in/400x400/media/fe/a6/68/1650358823/Bildschirmfoto%20vom%202022-03-24%2011-45-54.png

 

The url parameter size is 400x400 but actual css rendered image size is 400x249

 

I was struggeling with this problem:

See PNG Auswahl.png

On my product detail page the thumbnail size rendered is 65x40px, the format delivered by amazon is 3000x1871px and the original format I uploaded was 651x406px, how can I solve this problem?

Regards

 

Oliver

 
 

Gesendet: Dienstag, 19. April 2022 um 11:26 Uhr
Von: "tinect" ***@***.***>
An: "FriendsOfShopware/FroshPlatformThumbnailProcessor" ***@***.***>
Cc: "ollihfaa" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [FriendsOfShopware/FroshPlatformThumbnailProcessor] Height parameter in template ignored (Issue #49)


 

This repository you posted the issue belongs to the plugin for shopware 5. Therefore, I've transferred the issue.

Regarding the issue:
This is intended. Lazysizes calculates the width regarding the calculated aspectratio.
7f7973b#diff-e34d65258c5eb2cf1dee05e64355e4cc520dd816c4986e2b3c41b639e8b7c8abR8
