### ISSUE TITLE
SalesChannel Configuration inheritance does not apply

### ISSUE THREAD

**Issue by florianliebig** [FriendsOfShopware/FroshPlatformThumbnailProcessor#51]
### PHP Version

8.0

### Shopware Version

6.4.10.1

### Actual behaviour

You can configure the plugin ThumbnailPattern storewise using the standard shopware config inheritance and apply a different pattern per sales channel, but in the frontend only the "All Sales Channel" config gets applied

### Expected behaviour

The configuration I applied to the sales channel is applied for the thumbnail pattern and other configuration

### Steps to Reproduce?

Remove inheritance for a single sales channel in plugin configuration /admin#/sw/extension/config/FroshPlatformThumbnailProcessor - set a different value - clear cache & recompile themes - check frontend for the thumbnail url pattern.

The SystemConfigService#get takes the sales channel id as a secondary parameter, so it should be injected into https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/blob/master/src/Service/ThumbnailUrlTemplate.php#L37

**Comment by tinect** [comment]
Thank you. I will have a look at it soon.

Meanwhile, feel free to create a PR :-)

**Comment by tinect** [comment]
Hey @florianliebig 

I just had time to take a look into it.
There is no possibility to add media per saleschannel and there might be problems with import/exports adding this feature into the ThumbnailProcessor.

Keep in mind: everyone (plugins f.e.) requesting thumbnails will have to announce any saleschannelId to have it working. Sure, we might fail over to "all saleschannels" but there will occur unwanted behaviours.

That is the reason I think of disallowing setting this per saleschannel for this plugin.

What do you think?

**Comment by tinect** [comment]
Some more thoughts...
On the other hand... why not adding this feature for thumbnailprocessor :-) Should 3rd-parties just announcing the saleschannelId
