### ISSUE TITLE
Pictures are not shown, however the URL is correct / cloudflare

### ISSUE THREAD

**Issue by MarcusRobichon** [FriendsOfShopware/FroshPlatformThumbnailProcessor#58]
### PHP Version

7.4.29

### Shopware Version

6.4.11.1

### Actual behaviour

The URL is decoded correctly. When I copy the generated picture URL everything is fine and the picture is scaled correctly. However in the page the picture is not shown .. what I am missing here?

Example:

https://shopware.llg.gmbh/Weithals-Erlenmeyerkolben-PP-mit-Schraubverschluss-Nennvolumen-ml-500/4000105

Picture Code:

https://shopware.llg.gmbh/cdn-cgi/image/width=800,quality=85,format=auto/media/85/90/22/1654002075/7300355_1.jpg

### Expected behaviour

It should be shown corrctly :-)

### Steps to Reproduce?

See the examples.

**Comment by tinect** [comment]
did you check the devtools? there are js-errors thrown.

**Comment by MarcusRobichon** [comment]
It was the CCM19 Plugin which avoid the loading. Thanks for your help with that! It is working now!
