### ISSUE TITLE
ThumbnailProcessor Plugin --> https://prnt.sc/uaq034

### ISSUE THREAD

**Issue by talabyshop** [FriendsOfShopware/FroshPlatformThumbnailProcessor#6]
Hallo,

ich habe das plugin in meinem sw6 shop installiert.

Bei Aktivieren bekomme ich diese Fehlermeldung!

Ich hbae mein shop via ftp installiert (nicht via github)!

Danke & VG

Majed Eid

Plugin could not be activated due to error message 

"You have requested a non-existent parameter 

"shopware.filesystem.public.url". 

Did you mean one of these: 

"shopware.filesystem.private", 

"shopware.filesystem.private.type", 

"shopware.filesystem.public", 

"shopware.filesystem.public.type", 

"shopware.filesystem.public.config", 

"shopware.filesystem.public.config.root", 
"shopware.filesystem.temp", 

"shopware.filesystem.temp.type", 

"shopware.filesystem.temp.config"?"

**Comment by tinect** [comment]
Hallo @talabyshop,
Welche shopware-version setzen Sie ein? Es sollte für die aktuelle plugin-version min 6.3 sein.
Haben Sie das Plugin über den store bezogen?

Viele Grüsse

**Comment by tinect** [comment]
Plugin-Version 1.0.5 ist für alles darunter kompatibel.
Siehe composer.json

**Comment by talabyshop** [comment]
hallo,
wir nutzen sw 6.2!

**Comment by tinect** [comment]
Dann bitte die Version 1.0.5 nutzen. 

Viele Grüße
Sebastian

**Comment by talabyshop** [comment]
Ich benutze die Version 1.0.5 (https://prnt.sc/uax0or)
ich kann das plugin nicht aktivieren!
VG
Majed

**Comment by tinect** [comment]
Sieht mir danach aus, dass du die Versionen gemischt hast oder es ein Problem mit dem Cache gibt.
In der besagten Version wird der parameter noch gar nicht verwendet.
Bitte lade die v1.0.5 noch mal hoch und lösche den Cache.

**Comment by tinect** [comment]
Closed due to inactivity.
