### ISSUE TITLE
Update from 'ThumbnailProcessor incl. Lazy Loading and Webp-Support' 'Version: 1.0.26’ to ’Version 1.1.1'

### ISSUE THREAD

**Issue by nikkoch** [FriendsOfShopware/FroshPlatformThumbnailProcessor#66]
### Question

Hello and thank you for the great Shopware 6 extension! 

Can you tip us on update from 'ThumbnailProcessor incl. Lazy Loading and Webp-Support' 'Version: 1.0.26’ to ’Version 1.1.1' please. It is not available from the backend, so should we reinstall it? 

Start well!

**Comment by tinect** [comment]
Hi @nikkoch 

You need shopware 6.4.10.0 at least for the named plugin version. What version do you have installed?

You have installed the plugin via store or zip, not composer?

**Comment by nikkoch** [comment]
Hey tinect, thank you for the quick reply!

We have SW 6.4.8.0 and going to update to SW 6.4.15.2. We installed plugin via SW store.

**Comment by tinect** [comment]
As mentioned: You need 6.4.10.0 for any plugin update.

**Comment by nikkoch** [comment]
Thank you tinect for the swift replies! We love your extension 🤓
