### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Notice: Undefined offset: 1").

### ISSUE THREAD

**Issue by Oliverhorn** [FriendsOfShopware/FroshPlatformThumbnailProcessor#67]
### Question

Hi, 

i just tried to use the thunbnail processor in shopware 6.

My shopware version is: Aktuelle Version: 6.4.16.0
the thumbnail processor version is: 1.1.1

with the standard shopware theme, i got the following error:
 An exception has been thrown during the rendering of a template ("Notice: Undefined offset: 1").

the website isn't loading any more. 

Basically, the thumbnail creation is running fine. I'm using cloudimg and all pictures are already changed. 
When i'm looking into the media folders, each link to the media is changed to cloudimg, the thumbnail is showing and the fils can be viewed directly with its link.

But, as i said, the website is running into an error.
<img width="1162" alt="Bildschirmfoto 2022-10-18 um 11 38 50" src="https://user-images.githubusercontent.com/8182097/196396455-d1936635-9666-4633-9ecc-5ff49fdf3c6b.png">

Any idea?

After deactivating the thumbnail processor, the website is running as expected.

Thanks!
Oliver

**Comment by tinect** [comment]
https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/compare/1.1.1...master

Is this fix working for you? I missed releasing this fix :-( 

Background is that any of your images is not set, f.e. wrong set configurator options for variants

**Comment by Oliverhorn** [comment]
Hi, 

yes, that fixes the issue :)

thanks for your fast support!

regards
Oliver

**Comment by tinect** [comment]
release is out 👍
