### ISSUE TITLE
Lazyload missing from all.js

### ISSUE THREAD

**Issue by thesec** [FriendsOfShopware/FroshPlatformThumbnailProcessor#70]
### PHP Version

8.0.25

### Shopware Version

6.4.17.1

### Actual behaviour

While the plugin is installed, active and configured with a media path and showing in `plugins.json` ... `build-storefront.sh` does not result in the plugin's JS becoming part of `all.js` any longer.

### Expected behaviour

When executing `build-storefront.sh` with the plugin being installed and active `all.js` should include the plugin's JS.

### Steps to Reproduce?

One thing that has changed between installation from Shopware's store and the plugin working is an update from 6.4.16.1 to 6.4.17.1.

While I see the plugin listed as compatible up to 6.4.16.1 in the store, composer.json requires "^6.4.10" and will be compatible as is?

**Comment by tinect** [comment]
Hey,

you installed it by composer, zip from store or by git-source?

**Comment by thesec** [comment]
Hi, the plugin was initially installed and set up from within the backend's admin UI.

The source being used during deploy and update is the zip from the store, respectively the account.

**Comment by tinect** [comment]
Sadly, I cannot reproduce your error.

Can you please verify, your build shows `# Webpack Plugin Injector: Plugin "FroshPlatformThumbnailProcessor" injected with custom config` or similar?
Please verify there is a `frosh-platform-thumbnail-processor.js` within `src/Resources/app/storefront/dist/storefront/js/`.

Otherwise...
Could you please attach your `build-storefront.sh`-file to see which version you are having?

**Comment by thesec** [comment]
Which step should show `# Webpack ...`?

Find 
[build-storefront.sh.zip](https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/files/10025347/build-storefront.sh.zip)

... but the pointer to the js within dist has (a part of) the solution, I guess:
https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/blob/master/.gitignore
includes just that JS so it is not included in my repo.

Doesn't `build-storefront.sh` rebuild the dist'tribution files?
Which build command does do so?

**Comment by tinect** [comment]
> Which step should show # Webpack ...?

Run `build-storefront.sh``and scroll up a little bit. There should be all your plugins listed with this message.

Your build-storefront.sh looks correct.

> https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/blob/master/.gitignore
> includes just that JS so it is not included in my repo.

Yes, this could be the problem. Why do you have the plugin within your repo? Install it dynamically by composer.

> Doesn't build-storefront.sh rebuild the dist'tribution files?

Yes, just tested it by removing node_modules and the compiled `frosh-platform-thumbnail-processor.js`. They are created automatically by running `build-storefront.sh``.

While you are managing the plugin within your custom repo, there may be some problems. Please check alternatives.

**Comment by thesec** [comment]
So when `build-storefront.sh`does indeed build the js anyway, it should be built and included also when storing your plugin along all other ( which are mostly not publicly available ) inside a shopware project's git repository.

**Comment by tinect** [comment]
Did you verify what I've mentioned a few messages above?

**Comment by thesec** [comment]
Did so for local builds yesterday and verified `Webpack ...` showing up.

Remote builds did not show it which I verified just now. So I digged into it and found the bundle dump and other being excluded from within the process settings.

So thanks again for the second relevant hint where to look at 🙌
