### ISSUE TITLE
Service can*t handle URL Percent encoding

### ISSUE THREAD

**Issue by loesungsmittel** [FriendsOfShopware/FroshPlatformThumbnailProcessor#8]
Thanks for that plugin!

Running Shopware 6.3.1.1  the Media-URL is encoded and cloudimg cant' handle that url:

https://token.cloudimg.io/v7/https%3A//www.url.de/dev/public/media/d6/21/35/1594408736/imagename.png%26w%3D3000%26h%3D3000

If i replace %3A by : etc manually everything is fine. I don't know if this is an Plugin, SW or Config topic. 

Can someone help?

**Comment by tinect** [comment]
Hey @loesungsmittel 
Could you please post your template from pluginconfig?

Will check soon.

**Comment by tinect** [comment]
And, could you please tell me the plugin-version you are using?

**Comment by tinect** [comment]
I got it. Shopware uses encoding on media-urls. But I could catch it.
Could you please test this adjustment?
https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/commit/788111adb6f12403a4796b2444b629404e5930ff

**Comment by loesungsmittel** [comment]
It works! Thank you
