### ISSUE TITLE
Possible to ignore .ico (favicons)?

### ISSUE THREAD

**Issue by sr-mothership** [FriendsOfShopware/FroshPlatformThumbnailProcessor#84]
### Question

Hi there,

We successfully implemented the extension using Cloudflare.
However it seems that the request for the favicon now is using the same url schema:

![image](https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/assets/99882279/59ecbf09-432d-4f49-b4a8-b211710a250a)

Is it possible to ignore the favicon?

**Comment by tinect** [comment]
Hi,

there is no filter for specific files.

could you please check what is wrong with the url and check what could cause the error?

**Comment by sr-mothership** [comment]
I guess the extension takes every media folder into account when generating thumbnails? That would explain why it also generates the url for the favicon.

We are using v2.0.0 with sw 6.4 btw.

Is there an easy way we can get the extension to ignore the favicon?

**Comment by tinect** [comment]
This plugin does not generate any thumbnail. It manipulates the url of any media.

There might be solutions to do so. The code is really small. 

But this sounds more a hack, than a real fix. 
before doing so anyone might want to know what the real problem is.

**Comment by andreasemer** [comment]
> It manipulates the url of any media.

And this is the problem, CF can't handle .ico files. 

So maybe it makes sense to provide a input-field for blacklisted media types to bypass this isse. 

@tinect What do you think?

**Comment by tinect** [comment]
> And this is the problem, CF can't handle .ico files.
> 
> So maybe it makes sense to provide a input-field for blacklisted media types to bypass this issue.
> 

This sounds legit. I see there might be Services not supporting everything, additionally to the existing configuration for svg. PR is welcome.

But for the specific problem: why are you using ico instead of png?
This seems just legit as favicon.ico in public folder for default support, doesn‘t it?

**Comment by tinect** [comment]
Hey @andreasemer @sr-mothership 

could you please check the mentioned [PR](https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/pull/85) if it fits your needs?

Best Regards,
Sebastian

**Comment by sr-mothership** [comment]
> > And this is the problem, CF can't handle .ico files.
> > So maybe it makes sense to provide a input-field for blacklisted media types to bypass this issue.
> 
> This sounds legit. I see there might be Services not supporting everything, additionally to the existing configuration for svg. PR is welcome.
> 
> But for the specific problem: why are you using ico instead of png? This seems just legit as favicon.ico in public folder for default support, doesn‘t it?

Using .png instead of .ico solved the issue for us, thanks 👍 

Proposed new features in the PR look interesting 👀
