### ISSUE TITLE
Improve cloudimage config

### ISSUE THREAD

**Issue by loesungsmittel** [FriendsOfShopware/FroshPlatformThumbnailProcessor#9]
The configuration-template for cloudimage.io is not working properly. My Adjustments:
- the url of the shop should be written without https://. I don't know which variable provides that so i wrote domain.de
- After path should be a ? instead of &
- with func=bound the image fits into the given height/width values with maximum size. Without using that the image will be cropped and your shop looks strange. By using it the Shop looks like before.

https://token.cloudimg.io/v7/domain.de/{mediaPath}?w={width}&h={height}&func=bound

I would have pushed that change, but think it would be better if the code had the domain variable.

**Comment by TabOOn79** [comment]
I tested your Thumbnail-Pattern but for some reason all images got resized to 3000x3000 and than scaled to the needed value.

Example: 25145/logo_cs.gif?w=3000&h=3000&func=bound
logo should be 300x49

Is that a shopware related issue? It seems that with is always 3000px for some reason

I changed the Thumbnail-Pattern to:
https://token.cloudimg.io/v7/domain.de/{mediaPath}?w={width}&func=bound&org_if_sml=1
so no resize to a bigger size possible, which works for me

**Comment by tinect** [comment]
Hey @TabOOn79 I assume the logo does not use thumbnails, just different possible files for each viewport.
