### ISSUE TITLE
Cloudimage - abnormally high traffic since update to version 2.1.0

### ISSUE THREAD

**Issue by OrnaminMarketing** [FriendsOfShopware/FroshPlatformThumbnailProcessor#98]
### Question

Hey there,

last month we updated our shop to version 6.4.20.2 and also upgraded this plugin to version 2.1.0. The traffic reported by Cloudimage immediately spiked HARD and has since remained abnormally high:
![firefox_2vO3tKI3dI](https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/assets/108785951/c49f44a3-bd52-407e-b947-4f104f325cb8)

Unsurprisingly, our analytics tools tell us that visitor counts have remained the same. I contacted Cloudimage support to see if they could look into this. They checked the user agents from before and after the spike and noted that bot traffic seems to be the cause. For instance, the Pinterest bot suddenly was responsible for 100 MB of traffic in a single hour, when previously there was no sign of this.

Any idea what has happened here? It's not like bot traffic would suddenly jump up like this... or rather, bots and crawlers shouldn't be included in this in the first place. Were they excluded before and this somehow stopped in the new version?

On another note, our web agency pointed out that images in the backend are also served via CDN, which didn't happen previously. That seems quite unnecessary, why is that happening?

I'd appreciate any insight in this matter.

**Comment by OrnaminMarketing** [comment]
Hello tinect, thanks for the reply. Unfortunately, I'm no less confounded.

Our domains are of course whitelisted, but that's not related. Whitelisting prevents images from being served to other domains, but that's not what is happening. The images in our domains are being requested at a massively increased rate compared to before the update.
Even if the bots making those requests are legit, it just doesn't seem logical that a shopware (and plugin) update would result in them swarming to our website en masse. Furthermore, the primary purpose of using a CDN is to make sure human visitors can have the site load faster and get responsive images, I'm not certain bots require the same convenience.

**Comment by tinect** [comment]
Hey,

I'm sorry, I have no more ideas. I just cannot see any possible reason for updating the plugin resulting in your reported issue.

Additionally, I hope you find the reason
